// trade_engine.cpp
// -----------------------------------------------------------------------
// CryptoTrade Engine — persistent TCP order-intake service.
//
// Listens on port 9000 and accepts exactly ONE long-lived connection from
// the Node.js server (Node keeps a single shared socket open for every
// user's orders instead of dialing a fresh connection per request).
//
// Wire format, both directions: one JSON object per line (newline-
// delimited framing), so many messages can be pipelined back-to-back over
// the same socket:
//
//   Node -> Engine:  {"request_id":"...", "action":"PLACE_ORDER", ...}\n
//   Engine -> Node:  {"request_id":"...", "accepted":true, ...}\n
//
// request_id is generated by Node per-call and echoed back unchanged so
// Node can match a reply to the right pending request even when several
// orders (from different users) are in flight on the same connection at
// once.
//
// If the connection drops, the engine just goes back to accept() and
// waits for Node to reconnect — Node's client handles reconnect + backoff
// on its side.
//
// Build:
//   g++ -std=c++17 -O2 -I/path/to/asio/asio/include -DASIO_STANDALONE \
//       -pthread trade_engine.cpp -o trade_engine
//
// Run:
//   ./trade_engine
// -----------------------------------------------------------------------

#define ASIO_STANDALONE

#include <asio.hpp>
#include <iostream>
#include <sstream>
#include <string>
#include <optional>
#include <cmath>
#include <vector>

using asio::ip::tcp;

/* ═══════════════════════════════════════════════════════════════════════
   MINI JSON HELPERS
   ───────────────────────────────────────────────────────────────────────
   The wire format has a small, fixed set of keys (see enginePacket in
   engineClient.js), so a hand-rolled reader/writer is enough here — no
   need to pull in a full JSON library for this.
   ═══════════════════════════════════════════════════════════════════════ */
namespace tinyjson {

std::optional<std::string> extractRaw(const std::string& json, const std::string& key) {
    std::string pattern = "\"" + key + "\"";
    size_t keyPos = json.find(pattern);
    if (keyPos == std::string::npos) return std::nullopt;

    size_t colon = json.find(':', keyPos + pattern.size());
    if (colon == std::string::npos) return std::nullopt;

    size_t i = colon + 1;
    while (i < json.size() && std::isspace(static_cast<unsigned char>(json[i]))) i++;
    if (i >= json.size()) return std::nullopt;

    if (json[i] == '"') {
        size_t start = i + 1;
        size_t end = json.find('"', start);
        if (end == std::string::npos) return std::nullopt;
        return json.substr(start, end - start);
    }

    size_t start = i;
    size_t end = start;
    while (end < json.size() && json[end] != ',' && json[end] != '}' &&
           !std::isspace(static_cast<unsigned char>(json[end]))) {
        end++;
    }
    return json.substr(start, end - start);
}

std::optional<std::string> getString(const std::string& json, const std::string& key) {
    return extractRaw(json, key);
}

std::optional<double> getNumber(const std::string& json, const std::string& key) {
    auto raw = extractRaw(json, key);
    if (!raw || *raw == "null" || raw->empty()) return std::nullopt;
    try {
        return std::stod(*raw);
    } catch (...) {
        return std::nullopt;
    }
}

std::string esc(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '"' || c == '\\') out.push_back('\\');
        out.push_back(c);
    }
    return out;
}

} // namespace tinyjson

/* ═══════════════════════════════════════════════════════════════════════
   ORDER PACKET
   ═══════════════════════════════════════════════════════════════════════ */
struct OrderPacket {
    std::string request_id;
    std::string action;
    long long user_id = 0;
    long long wallet_id = 0;
    std::string symbol;
    std::string side;         // BUY | SELL
    std::string order_type;   // MARKET | LIMIT
    double quantity = 0;
    std::optional<double> limit_price;
    std::optional<double> take_profit_price;
    std::optional<double> stop_loss_price;
};

static const std::vector<std::string> SUPPORTED_SYMBOLS = {
    "BTC", "ETH", "BNB", "SOL", "XRP", "USDC"
};

bool isSupportedSymbol(const std::string& s) {
    for (const auto& sym : SUPPORTED_SYMBOLS) if (sym == s) return true;
    return false;
}

OrderPacket parsePacket(const std::string& json) {
    OrderPacket p;
    if (auto v = tinyjson::getString(json, "request_id")) p.request_id = *v;
    if (auto v = tinyjson::getString(json, "action")) p.action = *v;
    if (auto v = tinyjson::getNumber(json, "user_id")) p.user_id = static_cast<long long>(*v);
    if (auto v = tinyjson::getNumber(json, "wallet_id")) p.wallet_id = static_cast<long long>(*v);
    if (auto v = tinyjson::getString(json, "symbol")) p.symbol = *v;
    if (auto v = tinyjson::getString(json, "side")) p.side = *v;
    if (auto v = tinyjson::getString(json, "order_type")) p.order_type = *v;
    if (auto v = tinyjson::getNumber(json, "quantity")) p.quantity = *v;
    p.limit_price = tinyjson::getNumber(json, "limit_price");
    p.take_profit_price = tinyjson::getNumber(json, "take_profit_price");
    p.stop_loss_price = tinyjson::getNumber(json, "stop_loss_price");
    return p;
}

/* ═══════════════════════════════════════════════════════════════════════
   ENGINE-SIDE VALIDATION
   ───────────────────────────────────────────────────────────────────────
   Node already validated the order against a live market price before it
   ever reaches here. This is a defense-in-depth re-check on the packet
   shape itself.
   ═══════════════════════════════════════════════════════════════════════ */
struct EngineResult {
    std::string request_id;
    bool accepted;
    std::string message;
    std::vector<std::string> errors;
    long long engine_order_id = 0; // placeholder id, no DB/matching engine wired up yet
};

EngineResult validate(const OrderPacket& p) {
    std::vector<std::string> errors;

    if (p.action != "PLACE_ORDER") errors.push_back("Unsupported action");
    if (p.user_id <= 0) errors.push_back("Missing or invalid user_id");
    if (p.wallet_id <= 0) errors.push_back("Missing or invalid wallet_id");
    if (p.symbol.empty() || !isSupportedSymbol(p.symbol)) errors.push_back("Symbol is missing or unsupported");
    if (p.side != "BUY" && p.side != "SELL") errors.push_back("Side must be BUY or SELL");
    if (p.order_type != "MARKET" && p.order_type != "LIMIT") errors.push_back("order_type must be MARKET or LIMIT");
    if (p.quantity <= 0 || std::isnan(p.quantity)) errors.push_back("Quantity must be greater than 0");

    if (p.order_type == "LIMIT") {
        if (!p.limit_price || *p.limit_price <= 0) errors.push_back("LIMIT orders require a positive limit_price");
    } else if (p.order_type == "MARKET" && p.limit_price) {
        errors.push_back("MARKET orders must not include a limit_price");
    }

    if (p.take_profit_price && *p.take_profit_price <= 0) errors.push_back("take_profit_price must be greater than 0");
    if (p.stop_loss_price && *p.stop_loss_price <= 0) errors.push_back("stop_loss_price must be greater than 0");

    if (p.order_type == "LIMIT" && p.limit_price) {
        double lp = *p.limit_price;
        if (p.side == "BUY") {
            if (p.take_profit_price && *p.take_profit_price <= lp)
                errors.push_back("Take profit must be above the limit price");
            if (p.stop_loss_price && *p.stop_loss_price >= lp)
                errors.push_back("Stop loss must be below the limit price");
        } else if (p.side == "SELL") {
            if (p.take_profit_price && *p.take_profit_price >= lp)
                errors.push_back("Take profit must be below the limit price");
            if (p.stop_loss_price && *p.stop_loss_price <= lp)
                errors.push_back("Stop loss must be above the limit price");
        }
    }

    if (!errors.empty()) {
        return { p.request_id, false, "Engine rejected order", errors, 0 };
    }

    static long long counter = 1000;
    return { p.request_id, true, "Order accepted by engine", {}, ++counter };
}

std::string toJsonReply(const EngineResult& r) {
    std::ostringstream out;
    out << "{";
    out << "\"request_id\":\"" << tinyjson::esc(r.request_id) << "\",";
    out << "\"accepted\":" << (r.accepted ? "true" : "false") << ",";
    out << "\"message\":\"" << tinyjson::esc(r.message) << "\",";
    out << "\"engine_order_id\":" << r.engine_order_id << ",";
    out << "\"errors\":[";
    for (size_t i = 0; i < r.errors.size(); i++) {
        out << "\"" << tinyjson::esc(r.errors[i]) << "\"";
        if (i + 1 < r.errors.size()) out << ",";
    }
    out << "]";
    out << "}";
    return out.str();
}

/* ═══════════════════════════════════════════════════════════════════════
   HANDLE ONE PERSISTENT CONNECTION
   ───────────────────────────────────────────────────────────────────────
   Node opens this connection ONCE (shared across every user/order) and
   keeps it open. We keep the streambuf alive across the whole loop, since
   several pipelined messages can arrive in a single TCP read — read_until
   only consumes up to the first '\n' it finds, and any bytes after that
   stay buffered for the next iteration instead of being dropped.
   ═══════════════════════════════════════════════════════════════════════ */
void handleConnection(tcp::socket socket) {
    std::cout << "Node.js connected (shared connection): " << socket.remote_endpoint() << "\n";

    asio::streambuf buffer;

    while (true) {
        asio::error_code ec;
        asio::read_until(socket, buffer, '\n', ec);
        if (ec) {
            std::cout << "Connection closed by Node (" << ec.message() << ")\n\n";
            break;
        }

        std::istream is(&buffer);
        std::string line;
        std::getline(is, line);
        if (line.empty()) continue;

        std::cout << "Received: " << line << "\n";

        try {
            OrderPacket packet = parsePacket(line);
            EngineResult result = validate(packet);

            std::string reply = toJsonReply(result) + "\n";
            asio::write(socket, asio::buffer(reply));

            std::cout << (result.accepted ? "Accepted" : "Rejected")
                      << " [" << result.request_id << "] -> reply sent\n\n";
        } catch (std::exception& msgEx) {
            std::cerr << "Failed to process message: " << msgEx.what() << "\n\n";
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════
   MAIN — accept the (single) shared connection, then keep serving orders
   over it until it drops, then go back to waiting for a reconnect.
   ═══════════════════════════════════════════════════════════════════════ */
int main() {
    try {
        asio::io_context io;
        tcp::acceptor acceptor(io, tcp::endpoint(tcp::v4(), 9000));

        std::cout << "=====================================\n";
        std::cout << " CryptoTrade Engine Started\n";
        std::cout << " Listening on port 9000...\n";
        std::cout << " Expecting one shared connection from Node.\n";
        std::cout << "=====================================\n\n";

        while (true) {
            tcp::socket socket(io);
            acceptor.accept(socket);
            handleConnection(std::move(socket));
            // Loop back and wait for Node to reconnect if it ever drops.
        }
    } catch (std::exception& e) {
        std::cerr << "Fatal error: " << e.what() << std::endl;
    }

    return 0;
}